# Generated by Django 3.0.2 on 2020-04-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_nick', models.CharField(max_length=20, verbose_name='NickName')),
                ('users_email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='avatar')),
                ('photo_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=20, verbose_name='автор коммента')),
                ('comment_text', models.TextField(max_length=400, verbose_name='текст коммента')),
                ('comment_likes', models.IntegerField(verbose_name='лайки')),
                ('comment_dislikes', models.IntegerField(verbose_name='дизлайки')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('comment_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users')),
            ],
            options={
                'verbose_name': 'Мнение',
                'verbose_name_plural': 'Мнения',
            },
        ),
    ]
