# Generated by Django 3.0.2 on 2021-05-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_done',
            field=models.ManyToManyField(related_name='userscom2', to='comment.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_done',
            field=models.ManyToManyField(related_name='userscom', to='comment.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ondislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='onlike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users', unique='True'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_has_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='userOnRedaction',
            field=models.BooleanField(default=False, verbose_name='On redaction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Users'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, default='test.jpg', upload_to='avatar/%Y/%M/%D'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAge', models.IntegerField(blank=True, verbose_name='Age')),
                ('userTown', models.CharField(blank=True, default='не указано', max_length=20, verbose_name='Town')),
                ('userCountry', models.CharField(blank=True, default='не указано', max_length=20, verbose_name='Country')),
                ('userSex', models.CharField(blank=True, max_length=10, verbose_name='Sex')),
                ('userAbout', models.CharField(blank=True, max_length=100, verbose_name='About')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users', unique='True')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholeComments', models.IntegerField(verbose_name='Всего комментов: ')),
                ('wholeLikes', models.IntegerField(verbose_name='Всего лайков: ')),
                ('wholeDislikes', models.IntegerField(verbose_name='Всего дизлайков: ')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users', unique='True')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'managed': True,
            },
        ),
    ]
