# Generated by Django 3.0.2 on 2020-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
