# Generated by Django 3.0.2 on 2021-05-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210502_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalComments',
        ),
    ]
