# Generated by Django 3.0.2 on 2020-03-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200228_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='members',
            new_name='comment_id',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='comment_author',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='comment_dislikes',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='additionalcomments',
            name='pub_date',
        ),
    ]
