# Generated by Django 3.0.2 on 2020-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20200419_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, default='media/test.jpg', upload_to='avatar/%Y/%M/%D'),
        ),
    ]
