# Generated by Django 3.0.2 on 2020-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20200423_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='users_photo',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%M/%D'),
        ),
    ]
