# Generated by Django 3.0.2 on 2020-04-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_remove_users_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, default='test.jpg', upload_to='avatar/%Y/%M/%D'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAge', models.IntegerField(blank=True, verbose_name='Age')),
                ('userTown', models.CharField(blank=True, default='не указано', max_length=20, verbose_name='Town')),
                ('userCountry', models.CharField(blank=True, default='не указано', max_length=20, verbose_name='Country')),
                ('userSex', models.BooleanField(blank=True, verbose_name='Sex')),
                ('userAbout', models.CharField(blank=True, max_length=100, verbose_name='About')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comment.Users', unique='True')),
            ],
        ),
    ]
