# Generated by Django 3.0.2 on 2020-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20200427_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Информация о пользователе'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userOnRedaction',
            field=models.BooleanField(default=False, verbose_name='On redaction'),
        ),
    ]
