# Generated by Django 3.0.2 on 2020-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_auto_20200430_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userOnRedaction',
        ),
        migrations.AddField(
            model_name='users',
            name='userOnRedaction',
            field=models.BooleanField(default=False, verbose_name='On redaction'),
        ),
    ]
