# Generated by Django 3.0.2 on 2020-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0014_auto_20200430_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userSex',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sex'),
        ),
    ]
