# Generated by Django 3.0.2 on 2020-05-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0017_comment_dislike_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ondislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='onlike',
            field=models.BooleanField(default=False),
        ),
    ]
