# Generated by Django 3.0.2 on 2020-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0018_auto_20200509_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
